# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    diff: pr diff
    merge: pr merge
    close: issue close
    add: issue create --title
    mine: issue list -a @me
    e: issue edit
    label: issue edit --add-label
    claim: issue edit --add-assignee @me
    rmlabel: issue edit --remove-label

    br-pr-help: "! echo \"gh br-pr\" 'command arguments:\n
                - jira-issue (only number)\n
                - change-type (feat, fix, docs, style, refactor, perf, test, chore)\n
                - change-location (component)\n
                - change-description (multi word description)'"
    br-pr: "!gh pr create --base=main --title=\"[BR-$1] $2($3): ${@:4}\" --fill"

    br-release-help: "! echo \"gh pr-release\" 'command arguments:\n
                    - release-number (autoincremental within the same day) \n
                    - release-description (multi word description)'"
    br-release: "! pr_name=\"[$(date +%Y.%m.%d)-$1] release: ${@:2}\";
                 git checkout main;
                 git pull;
                 gh pr create --base=prod --title=${pr_name} --fill;
                 echo \"creating release to prod with name ${pr_name}\""
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
