git_protocol: ssh
editor: nvim
prompt: enabled
pager: less
aliases:
    co: pr checkout
    diff: pr diff
    merge: pr merge
    close: issue close
    add: issue create --title
    mine: issue list -a @me
    e: issue edit
    label: issue edit --add-label
    claim: issue edit --add-assignee @me
    rmlabel: issue edit --remove-label

    # TODO(santiagotoscanini): Create --help flags
    br-pr:           "! source $XDG_CONFIG_HOME/zsh/git-alias.work.zsh && brPullRequest"
    br-pr-help:      "! source $XDG_CONFIG_HOME/zsh/git-alias.work.zsh && brPullRequestHelp"
    br-release:      "! source $XDG_CONFIG_HOME/zsh/git-alias.work.zsh && brRelease"
    br-release-help: "! source $XDG_CONFIG_HOME/zsh/git-alias.work.zsh && brReleaseHelp"

# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
browser:
