git_protocol: ssh
editor: nvim
prompt: enabled
pager: less
aliases:
    co: pr checkout
    diff: pr diff
    merge: pr merge
    close: issue close
    add: issue create --title
    mine: issue list -a @me
    e: issue edit
    label: issue edit --add-label
    claim: issue edit --add-assignee @me
    rmlabel: issue edit --remove-label

    br-pr-help: "! brPullRequestHelp"
    br-pr: "!gh pr create --base=main --title=\"[BR-$1] $2($3): ${@:4}\" --fill"

    br-release-help: "! echo \"gh pr-release\" 'command arguments:\n
                    - release-number (autoincremental within the same day) \n
                    - release-description (multi word description)'"
    br-release: "! pr_name=\"[$(date +%Y.%m.%d)-$1] release: ${@:2}\";
                 git checkout main;
                 git pull;
                 gh pr create --base=prod --title=${pr_name} --fill;
                 echo \"creating release to prod with name ${pr_name}\""
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
browser:
