# ===========================================
# GitHub CLI Hosts Configuration
# ===========================================

# Configuration for github.com
github.com:
  # Main user account
  user: santiagotoscanini

  # Protocol for git operations (ssh or https)
  git_protocol: ssh
