[[colors.indexed_colors]]
color = "0xb15c00"
index = 16

[[colors.indexed_colors]]
color = "0xc64343"
index = 17

[colors.bright]
black = "0xa1a6c5"
blue = "0x2e7de9"
cyan = "0x007197"
green = "0x587539"
magenta = "0x9854f1"
red = "0xf52a65"
white = "0x3760bf"
yellow = "0x8c6c3e"

[colors.normal]
black = "0xe9e9ed"
blue = "0x2e7de9"
cyan = "0x007197"
green = "0x587539"
magenta = "0x9854f1"
red = "0xf52a65"
white = "0x6172b0"
yellow = "0x8c6c3e"

[colors.primary]
background = "0xfafafa"
foreground = "0x3760bf"

# [[schemes.material_ligther.indexed_colors]]
# color = "0xb15c00"
# index = 16
#
# [[schemes.material_ligther.indexed_colors]]
# color = "0xc64343"
# index = 17
#
# [schemes.material_ligther.bright]
# black = "0xa1a6c5"
# blue = "0x2e7de9"
# cyan = "0x007197"
# green = "0x587539"
# magenta = "0x9854f1"
# red = "0xf52a65"
# white = "0x3760bf"
# yellow = "0x8c6c3e"
#
# [schemes.material_ligther.normal]
# black = "0xe9e9ed"
# blue = "0x2e7de9"
# cyan = "0x007197"
# green = "0x587539"
# magenta = "0x9854f1"
# red = "0xf52a65"
# white = "0x6172b0"
# yellow = "0x8c6c3e"
#
# [schemes.material_ligther.primary]
# background = "0xfafafa"
# foreground = "0x3760bf"
#
# [[schemes.tokyonight_night.indexed_colors]]
# color = "0xff9e64"
# index = 16
#
# [[schemes.tokyonight_night.indexed_colors]]
# color = "0xdb4b4b"
# index = 17
#
# [schemes.tokyonight_night.bright]
# black = "0x414868"
# blue = "0x7aa2f7"
# cyan = "0x7dcfff"
# green = "0x9ece6a"
# magenta = "0xbb9af7"
# red = "0xf7768e"
# white = "0xc0caf5"
# yellow = "0xe0af68"
#
# [schemes.tokyonight_night.normal]
# black = "0x1D202F"
# blue = "0x7aa2f7"
# cyan = "0x7dcfff"
# green = "0x9ece6a"
# magenta = "0xbb9af7"
# red = "0xf7768e"
# white = "0xa9b1d6"
# yellow = "0xe0af68"
#
# [schemes.tokyonight_night.primary]
# background = "0x24283b"
# foreground = "0xc0caf5"
