# ===========================================
# ~/.config/zsh/.zshrc
# Sourced only for interactive shells
# ===========================================

# =========== Powerlevel10k Instant Prompt ===========
# Print a minimal prompt immediately so the shell feels responsive while the
# rest of init runs in the background. Must stay at the top: any prior code
# that prints output or reads input would be hidden behind the instant prompt
# and break it. Run `p10k configure` to customize the prompt style.
# Reference: https://github.com/romkatv/powerlevel10k#instant-prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Fix Homebrew PATH ordering issue
# macOS calls /etc/zprofile after .zshenv which adds some system paths before homebrew's.
# This ensures Homebrew binaries take precedence over system ones.
typeset -U PATH path  # Ensure PATH contains no duplicates
[[ -d /opt/homebrew/bin ]] && path=(/opt/homebrew/bin $path)

# History configuration
HISTSIZE=50000                   # Maximum events in internal history
SAVEHIST=10000                   # Maximum events in history file
setopt HIST_IGNORE_ALL_DUPS      # Don't record duplicates
setopt HIST_SAVE_NO_DUPS         # Don't write duplicates to history file
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks
setopt EXTENDED_HISTORY          # Record timestamp of command
setopt SHARE_HISTORY             # Share history between sessions
setopt HIST_IGNORE_SPACE         # Ignore commands that start with a space (useful for commands including passwords)

# Add custom completions to fpath (must be before Oh-My-Zsh loads compinit)
fpath=($ZDOTDIR/completions $fpath)

# Load additional configuration files
[[ -f $ZDOTDIR/alias.zsh ]] && source $ZDOTDIR/alias.zsh  # Load aliases

# Per-machine hooks around oh-my-zsh load. Defined in work.zsh on machines
# that need to compensate for slow fork+exec (e.g. SentinelOne EDR).
(( $+functions[_work_pre_omz_load] )) && _work_pre_omz_load
[[ -f $ZDOTDIR/oh-my.zsh ]] && source $ZDOTDIR/oh-my.zsh  # Load Oh-My-Zsh config
(( $+functions[_work_post_omz_load] )) && _work_post_omz_load

# Register custom completions (must be after oh-my-zsh loads compinit)
compdef _dots dots

# Santree shell integration. The cache is written and self-invalidated by
# santree itself (see shell/init.zsh.njk in the santree repo); we just source
# it here, with a one-time fallback on first run when the cache doesn't exist.
_si=${XDG_CACHE_HOME:-$HOME/.cache}/santree/init-zsh.zsh
[[ -f $_si ]] && source $_si || eval "$(santree helpers shell-init zsh)"
unset _si

# Powerlevel10k user customization (generated by `p10k configure`).
# Lives in $ZDOTDIR because p10k follows ZDOTDIR; tracked in dotfiles so the
# same prompt style applies on every machine. Re-run `p10k configure` to update.
[[ -f $ZDOTDIR/.p10k.zsh ]] && source $ZDOTDIR/.p10k.zsh

# Local customizations (if any)
[[ -f $ZDOTDIR/local.zsh ]] && source $ZDOTDIR/local.zsh

# pnpm
export PNPM_HOME="/Users/stoscanini/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
